### ISSUE TITLE
crgrep - name already in use since 2013

### ISSUE THREAD

**Issue by craigryan** [CWaYNe/crgrep#1]
I'd like to suggest you use a name other than 'crgrep' for your tool, I have an existing open source tool of the same name which is well established. A simple google search of 'crgrep' lists it in the top four results making it obvious the name is already being used as a 'command line utility'.

https://bitbucket.org/cryanfuse/crgrep
https://sourceforge.net/projects/crgrep/

**Comment by ibkernel** [comment]
Sure. Thank you for the heads up.
